### PR TITLE
deflate fix with w+ mode

### PR DESCRIPTION
**Pull request by HarithaIBM**
deflate fix with w+ mode instead of writing it in w+b mode.

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Does this reduce test case failures or fix a particular bug?

**Comment by HarithaIBM** [comment]
> Does this reduce test case failures or fix a particular bug?

Yes, Mike It fixes issue related to https://github.com/ZOSOpenTools/groovyport/issues/4

**Review by IgorTodorovskiIBM — APPROVED** [review]
lgtm

**Review by MikeFultonDev — APPROVED** [review]
LGTM

**Pull request merged**
